### PR TITLE
add gemfile to hint that compass is needed

### PR DESCRIPTION
**Pull request by peter-mouland**
compass isn't mentioned anywhere, at least this will give people a hint

### CODE REVIEW

**Comment by aendrew** [comment]
@chrishutchinson LGTM, but is there anything Compass is specifically needed for? Could that just be replaced altogether with node-sass?

**Comment by peter-mouland** [comment]
that would be my preference too. I've only just started looking at it so haven't got far into the code yet - if when playing with it some more it seems like a quick job, i'll do a PR for that.  In the meantime i think this still makes sense as you don't even need to bump the version number.

**Comment by aendrew** [comment]
@peter-mouland Did you mean to close this? @chrishutchinson is out of country at the moment, but I'm sure he'd be interested in merging once back.

**Comment by peter-mouland** [comment]
nope, i merged it into my fork - didn't realise it would get closed here too. restored.

**Pull request merged**
